debian:
  release: bullseye
  apt:
    bootstrap_cache_server_address:
      cache:3142
    server_address:
      ftp.us.debian.org
    lists:
      backports: |
        deb http://ftp.us.debian.org/debian bullseye-backports main non-free contrib
        deb-src http://ftp.us.debian.org/debian bullseye-backports main non-free contrib
      extras: |
        deb http://ftp.us.debian.org/debian bullseye non-free contrib
        deb-src http://ftp.us.debian.org/debian bullseye non-free contrib
      security: |
        # Nothing yet
    packages:
      standard: >
        linux-image-amd64
        live-boot
        systemd-sysv
        network-manager isc-dhcp-client net-tools iproute2 wireless-tools wpagui
        curl openssh-client sudo firewalld
        vlc
        openbox lightdm xserver-xorg-core xserver-xorg xinit xterm i3lock xautolock
        netcat socat nmap screen telnet ser2net can-utils
        inetutils-ping thunar network-manager nano less firefox-esr gnome-screensaver
        coreutils fdisk gparted cryptsetup testdisk pciutils
        firmware-linux firmware-linux-free firmware-linux-nonfree firmware-misc-nonfree amd64-microcode intel-microcode firmware-iwlwifi firmware-realtek firmware-ralink firmware-brcm80211 firmware-bnx2x firmware-atheros firmware-ath9k-htc
        pixiewps aircrack-ng reaver wireshark tshark transmission-gtk hashcat john john-data wamerican-insane
        xfce4-terminal git rsync geany patch python2 python3 nginx vim unzip build-essential git-lfs
      download_only: >
        firmware-b43-installer firmware-ipw2x00
      backports: >
        # Nothing yet
user:
  name: myuser
  password: password
commands:
  # Any arbitrary custom commands to run in the chroot.
  chroot: |
    ln -s /usr/bin/python2 /usr/bin/python
    firewall-offline-cmd --remove-service=ssh
